### ISSUE TITLE
Add Support For Polygons

### ISSUE THREAD

**Issue by traik06** [abrman/shp-kit#11] opened 2024-11-05 19:07 UTC
Hello I am not able to convert 3D polygons to shp file.

const coordinates = [
[
[0, 0, 0], // Vertex 1: x, y, z
[0, 10, 0], // Vertex 2: x, y, z
[10, 10, 0],// Vertex 3: x, y, z
[10, 0, 0], // Vertex 4: x, y, z
[0, 0, 0] // Closing vertex to complete the polygon
]
];

After conversion, I am getting only X and Y values, not Z values. Is there plans to add support to this?

**Comment by abrman** [comment] 2024-11-05 19:10
Hey! I'm not in active development of shp-kit, but I'd like to help you if I can.
Can you please provide the shapefile you're using?

Correction: I'm realizing that you might be trying to create a shapefile in javascript, likely shapefile of type PolygonZ which is not supported. Any chance a PolylineZ would satisfy your needs? Where's the end product going to be used?

**Comment by traik06** [comment] 2024-11-05 19:13
So mainly I have some GeoJSON that I am trying to generate some 3D polygons from and export it into a shapefile but when the shapefile is generated the shapfile only contains x and y values. I'm imagining I would need to be using PolygonZ to accomplish this. But it seems from your supported types that PolygonZ is not supported

```
const points = {
      type: 'FeatureCollection',
      features: [],
    };

const template = {
        type: 'Feature',
        geometry: {
          type: 'Polygon',
          coordinates: [coords],
        },
        properties: {
          name: region.name,
        },
      };

const test = shpKit.shpWrite(points, 'Polygon');
```

here I am then creating a template and pushing it into the features array. The error message I get is that Error: Shapefile type not currently supported

**Comment by traik06** [comment] 2024-11-05 19:21
> Hey! I'm not in active development of shp-kit, but I'd like to help you if I can. Can you please provide the shapefile you're using?
> 
> Correction: I'm realizing that you might be trying to create a shapefile in javascript, likely shapefile of type PolygonZ which is not supported. Any chance a PolylineZ would satisfy your needs? Where's the end product going to be used?

It would just be used in CAD environments to view linework

**Comment by abrman** [comment] 2024-11-05 20:08
Hey @traik06,

Assuming you are able to convert polylines to polygons in your CAD application, you should be good to go with the PolyLineZ which creates a 3D Polyline (testing in Autodesk Civil 3D) from where converting to a polygon shouldn't be too difficult.

```
const geojson = {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        properties: {},
        geometry: {
          coordinates: [
            [
              [0, 0, 0],
              [0, 10, 1],
              [10, 10, 2],
              [10, 0, 3],
              [0, 0, 0],
            ],
          ],
          type: "Polygon",
        },
      },
    ],
  };

  shpWriteZip("Test", geojson, "PolyLineZ", {}, true);
};
```

I'm reading on the whitepaper and trying to understand why I avoided programming the polygon type support in the first place, and I think it's because the implementation of polygon with holes between geojson and shapefile isn't identical, and would need to be handled within shp-kit. 

Specfically in shapefiles:

> A polygon consists of one or more rings. A ring is a connected sequence of four or more points that form a closed, non-self-intersecting loop. A polygon may contain multiple outer rings. The order of vertices or orientation for a ring indicates which side of the ring is the interior of the polygon. The neighborhood to the right of an observer walking along the ring in vertex order is the neighborhood inside the polygon. Vertices of rings defining holes in polygons are in a counterclockwise direction. Vertices for a single, ringed polygon are, therefore, always in clockwise order. The rings of a polygon are referred to as its parts.
> Because this specification does not forbid consecutive points with identical coordinates, shapefile readers must handle such cases. On the other hand, the degenerate, zero length or zero area parts that might result are not allowed.

For Geojson:
> To specify a constraint specific to Polygons, it is useful to introduce the concept of a linear ring:
> -  A linear ring is a closed LineString with four or more positions.
> -  The first and last positions are equivalent, and they MUST contain identical values; their representation SHOULD also be identical.
> -  A linear ring is the boundary of a surface or the boundary of a hole in a surface.
> -  A linear ring MUST follow the right-hand rule with respect to the area it bounds, i.e., exterior rings are counterclockwise, and holes are clockwise.
>
> Note: the [[GJ2008](https://datatracker.ietf.org/doc/html/rfc7946#ref-GJ2008)] specification did not discuss linear ring winding order.  For backwards compatibility, parsers SHOULD NOT reject Polygons that do not follow the right-hand rule.
> Though a linear ring is not explicitly represented as a GeoJSON geometry type, it leads to a canonical formulation of the Polygon geometry type definition as follows:
> - For type "Polygon", the "coordinates" member MUST be an array of linear ring coordinate arrays.
> - For Polygons with more than one of these rings, the first MUST be the exterior ring, and any others MUST be interior rings.  The exterior ring bounds the surface, and the interior rings (if present) bound holes within the surface.

shp-kit would need to check which of the LineStrings form the interior of the polygon with holes, and which form the exterior. Geojson have the clockwise, counterclockwise rule switched, and while geojson isn't strict with the direction of a linestring, shapefile is, so shp-kit would need to do checks to determine which of the linestrings are exterior, and which interior, and reverse direction per need, keeping in mind that you can have additional islands inside of a donut hole.

Additionally would be nice to implement:
- Check and make sure that none of the polygon LineStrings are intersecting, and if they are, throw an error. Without this check invalid shapefiles would be generated.
- Ensure ring closure
- Remove redundant points

Feel free to consider making a pull request if you're down for the challenge, use the partial functionality of the shp-kit utilizing polylineZ. It seems like polyline and polygon shp structure is identical per whitepaper, however the logic of above would need to be implemented.

Links to whitepapers:
[Shapefile](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf)
[GeoJSON](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6)

The reader and the writer would need to be created, likely something similar to the polyline counterpart
[shp-kit/src/private/readers/PolyLine.ts](https://github.com/abrman/shp-kit/blob/ae33d67a1cfabb4628639e22b9cf647f612f7c61/src/private/readers/PolyLine.ts)
[shp-kit/src/private/writers/PolyLine.ts](https://github.com/abrman/shp-kit/blob/ae33d67a1cfabb4628639e22b9cf647f612f7c61/src/private/writers/PolyLine.ts)

and then reflect the implementation in the index.ts for readers and writers
[shp-kit/src/private/readers/index.ts](https://github.com/abrman/shp-kit/blob/ae33d67a1cfabb4628639e22b9cf647f612f7c61/src/private/readers/index.ts)
[shp-kit/src/private/writers/index.ts](https://github.com/abrman/shp-kit/blob/ae33d67a1cfabb4628639e22b9cf647f612f7c61/src/private/writers/index.ts)

I may look into polylineZ in the future with the notes from above if there's going to be a compelling reason.
Good luck @traik06, please let me know if polylineZ was able to assist you in your needs or polylineZ will be necessary

**Comment by traik06** [comment] 2024-11-06 17:26
@abrman 

So with the current functionality of the `shp-kit` I should be able to just use `PolyLineZ `and then convert them to Polygons in CAD, etc...? 

I also noticed in the `geojson `example above you provided that it is labeled as `Polygon`, and in the `shpWriteZip` function it is called as `PolyLineZ`. 

Is that how it would need to be implemented?

**Comment by abrman** [comment] 2024-11-06 17:47
@traik06

> So with the current functionality of the shp-kit I should be able to just use PolyLineZ and then convert them to Polygons in CAD, etc...?

I would hope so, however different CAD applications may vary in their tools for working with 3D polygons and so I hope you'll be able to utilize what is available. (The shape of a 3D Polygon is quite ambiguous when a it's outer edge isn't planar, as it doesn't specify triangulation, and such it could be represented in a variety of ways in 3D space, then consider 3D polygons with donut holes and you're now in a geometrical conundrum)

Since shapefiles don't support having multiple types of geometry in a single file, such as lines and point, or lines and polygons, every shapefile is only a single type of geometry file - Because of this shapefile format limitation, the direction I went forward with for shp-kit is that of wide geojson acceptance. 

Since you define the output type, such as PolylineZ, it will break down more complex types such as polygons and process them as polylines rather than skipping over them (or requiring you to convert all geojson into strict feature types). Similarly if you export a points type shapefile, a geojson containing polygons, polylines and points will be broken into the simplest primitives, points, and exported. The opposite approach would be skipping over features not fitting the format, but that would likely cause more headache than current implementation (I'd love to know if you disagree)

> Is that how it would need to be implemented?

You can use `LineString`, `MultiLineString`, `Polygon`, or `MultiPolygon` when exporting PolylineZ shapefile and all the geojson feature types listed will be exported. `Point` and `MultiPoint` should be ignored from the provided geojson when exporting `PolylineZ`.

Hope that answers your question.

**Comment by traik06** [comment] 2024-11-06 17:55
@abrman I understand, my instance there isn't going to any places where there is a hole in the polygon such as a donut. they will be just whole segments with no holes. I'm relatively new to the SHP file formatting and how it all needs to be implemented correctly

In the example below it would always be the blue polygon to the right never an instance of a hole in the middle of a polygon

![image](https://github.com/user-attachments/assets/4d01bd97-c998-4355-be8a-b1d32631dc93)

**Comment by abrman** [comment] 2024-11-06 19:13
`shp-kit` won't have partial support implementation on the main branch.
From what you're saying it sound like forking `shp-kit` and modifying polyline writer to fit your needs might be the way to go.

Consider forking and trying  `shpWriteZip(_, _, "PolygonZ");` after implementing changes below:

[shp-kit/src/private/writers/PolyLine.ts](https://github.com/abrman/shp-kit/blob/ae33d67a1cfabb4628639e22b9cf647f612f7c61/src/private/writers/PolyLine.ts)
Remove lines 14 and 16
```
      f.geometry.type === "LineString" ||
      (o.bundleMultiTypes && f.geometry.type === "MultiLineString") ||
```

Update line 125:
```
    if (shapefileNumberTypeToStringType(shpTypeNumber) === "PolygonZ") {
```
[shp-kit/src/private/writers/index.ts](https://github.com/abrman/shp-kit/blob/ae33d67a1cfabb4628639e22b9cf647f612f7c61/src/private/writers/index.ts)
Update line 12:
```
  15: PolyLineWriter,
```

After that run `npm run build` and copy built bundle into your project, or see how you can install packages from github.
Should look something like this, but it's been a while since I did so. I'm sure google search will be helpful.
```
package.json
===================
"dependencies": {
...
"shapefile": "github:traik06/shp-kit",
}
```

This should work as the whitepaper for shapefile reads `The PolygonZ structure is identical to the PolyLineZ structure...` and thus if you make sure you make sure your coordinate lists always follow the clockwise direction (I think), and never intersect, your file should be valid and readable by CAD applications, but no guarantees.

Let me know if this works for you.

**Comment by traik06** [comment] 2024-11-08 20:04
@abrman 
Below is the code i'm testing with and the issue im getting when im downloading it is the files that are zipped are empty 

```javascript

const geojson = {
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          properties: {},
          geometry: {
            coordinates: [
              [
                [
                  -79.89884579800741,
                  40.52453822514474,
                  12
                ],
                [
                  -79.89875714969106,
                  40.524557477726574,
                  34
                ],
                [
                  -79.89884579800741,
                  40.52453822514474,
                  12
                ]
              ]
            ],
            type: "PolygonZ"
          }
        }
      ]
    }

const { shp, shx, dbf } = await shpKit.shpWrite(geojson, 'PolygonZ', {});

let zip = new JSZip();
zip.file('regions.shp', shp);
zip.file('regions.shx', shx);
zip.file('regions.dbf', dbf);
const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });
const zippedFile = zipBuffer.buffer.slice(zipBuffer.byteOffset, zipBuffer.byteOffset + zipBuffer.byteLength);
```

**Comment by abrman** [comment] 2024-11-08 21:58
I forgot to call out one more change in Polyline.ts on lines 32 and 33,
`PolylineM` should be `PolygonM`, and `PolylineZ` should be `PolygonZ` as you see below
```ts
  if (typeString === "PolygonM") polyline_record_length_bytes += 16 + coordinates.length * 8;
  if (typeString === "PolygonZ") polyline_record_length_bytes += 32 + coordinates.length * 16;
```

I've adjusted your snippet and added comments

```ts
const geojson = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {},
      geometry: {
        coordinates: [
          [
            [-79.89884579800741, 40.52453822514474, 12],
            [-79.89875714969106, 40.524557477726574, 34],
            // Notice: Added additional coordinate as polygons need to contain at-least 4 coordinates, with the 1st and last being identical
            [-79.89875714969106, 40.5245678726574, 34],
            [-79.89884579800741, 40.52453822514474, 12],
          ],
        ],
        // Notice: I've corrected "PolygonZ" to "Polygon", as for the geojson we need to stick to the GeoJSON specification, where closest thing to PolygonZ of the shapefile format is "Polygon"
        type: "Polygon",
      },
    },
  ],
} as FeatureCollection; // ignore if you're using plain javascript, if using typescript import { FeatureCollection } from "geojson";

// Generate zip via shp-kit
const filename = "Github_example.zip";
const zipBlob = await shpWriteZip(filename, geojson, "PolygonZ");

// Save blob via node
const buffer = Buffer.from(await zipBlob.arrayBuffer());
fs.writeFile(`./${filename}`, buffer, (err) => {
  if (err) throw err;
  console.log(`Blob saved successfully to working directory as ${filename}!`);
});


// Alternatively if you intend to run in a browser you can trigger download via 5th parameter of shpWriteZip (download: boolean)
const filename = "Github_example.zip";
const zipBlob = await shpWriteZip(filename, geojson, "PolygonZ", {}, true);
```

I've tested on my end and generated a shapefile that proved to be valid via [mapshaper](https://mapshaper.org/) although the best validity test if your CAD application.

As always, let me know if this works for you.

**Comment by traik06** [comment] 2024-11-12 17:17
@abrman 

I'm so close I feel on where I need this to be. When I try to use this test data 

```javascript
const geojson = {
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          properties: {},
          geometry: {
            coordinates: [
              [
                [
                  -86.78641957092839,
                  33.12193634107881,
                  65
                ],
                [
                  -86.78735311336958,
                  33.12006667812149,
                  56
                ],
                [
                  -86.78505984606862,
                  33.119879709636635,
                  56
                ],
                [
                  -86.7837812988126,
                  33.12151142117442,
                  56
                ],
                [
                  -86.78380159321324,
                  33.122599212023744,
                  56
                ],
                [
                  -86.78641957092839,
                  33.12193634107881,
                  65
                ]
              ]
            ],
            type: "Polygon"
          }
        },
        {
          type: "Feature",
          properties: {},
          geometry: {
            coordinates: [
              [
                [
                  -86.78494145733295,
                  33.12348397509187,
                  67
                ],
                [
                  -86.78518499014336,
                  33.122430188528,
                  56
                ],
                [
                  -86.78356143807218,
                  33.12282111082557,
                  56
                ],
                [
                  -86.78345996606778,
                  33.12090047585342,
                  56
                ],
                [
                  -86.78205965240596,
                  33.12146137359524,
                  56
                ],
                [
                  -86.78281054523904,
                  33.124418775169175,
                  56
                ],
                [
                  -86.78494145733295,
                  33.12348397509187,
                  67
                ]
              ]
            ],
            type: "Polygon"
          }
        },
        {
          type: "Feature",
          properties: {},
          geometry: {
            coordinates: [
              [
                [
                  -86.78209686353829,
                  33.12208931174068,
                  67
                ],
                [
                  -86.78065933874453,
                  33.12270213465888,
                  56
                ],
                [
                  -86.77990844591146,
                  33.123806907152826,
                  56
                ],
                [
                  -86.77974609070436,
                  33.12475870000226,
                  56
                ],
                [
                  -86.78258392915924,
                  33.12407790609923,
                  56
                ],
                [
                  -86.78209686353829,
                  33.12208931174068,
                  67
                ]
              ]
            ],
            type: "Polygon"
          }
        }
      ]
    }

    const { shp, shx, dbf } = await shpKit.shpWrite(geojson, 'PolygonZ');

    let zip = new JSZip();
    zip.file('regions.shp', shp);
    zip.file('regions.shx', shx);
    zip.file('regions.dbf', dbf);
    console.log('zip', zip)
    const zipBuffer = await zip.generateAsync({ type: "arraybuffer" });

    // Set appropriate headers for ArrayBuffer response
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', 'attachment; filename=regions.zip');

    // Send the ArrayBuffer as the response body
    return res.send(Buffer.from(zipBuffer));
```

I get the following error

`UnhandledPromiseRejectionWarning: RangeError: Offset is outside the bounds of the DataView`

I changed the `geojson` and it exports correctly with 1 and 2 polygons but only shows one polygon. As soon as I go to export 3 polygons that error occurs. 

### Current Testing 
1. `geojson` containing 1 polygon
- properly exports and shows the 1 polygon on the map

2. `geojson` containing 2 polygons
- properly exports but still only shows 1 polygon on the map and not 2

3. `geojson` containing 3 polygons
- error occurs of the `Offset is outside the bounds of the DataView`

There will be instances where there can be 60+ different polygons that are getting exported. Is there a max limit of polygons that can be exported?

**Comment by abrman** [comment] 2024-11-12 17:30
`UnhandledPromiseRejectionWarning: RangeError: Offset is outside the bounds of the DataView` indicated a bug in the shp-kit code rather than shapefile limitations, or the provided input.

Shapefile is a binary format and before writing any data to the file, the file needs to be created with just zeros - imagine preparing a canvas of a specific size before you start writing data. This error indicates that data is attempted to be written outside of the file length (canvas size).

Please try the geojson input causing issues with an unmodified `shp-kit` (not from your fork) and use `PolylineZ` as export type. If that generates a file without any errors, the problem is with the `PolygonZ` implementation in your fork. If the same error occurs on `PolylineZ` this will be a valid bug existing in `shp-kit`s implementation of `PolylineZ` export and would need to be resolved.

Please report your findings.

**Comment by traik06** [comment] 2024-11-12 17:38
@abrman 

I used the current version of `shp-kit` with this implementation and my results were the same with `PolyLineZ` where it only showed one polygon

```javascript
const geojson = {
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          properties: {},
          geometry: {
            coordinates: [
              [
                [
                  -86.78641957092839,
                  33.12193634107881,
                  65
                ],
                [
                  -86.78735311336958,
                  33.12006667812149,
                  56
                ],
                [
                  -86.78505984606862,
                  33.119879709636635,
                  56
                ],
                [
                  -86.7837812988126,
                  33.12151142117442,
                  56
                ],
                [
                  -86.78380159321324,
                  33.122599212023744,
                  56
                ],
                [
                  -86.78641957092839,
                  33.12193634107881,
                  65
                ]
              ]
            ],
            type: "Polygon"
          }
        },
        {
          type: "Feature",
          properties: {},
          geometry: {
            coordinates: [
              [
                [
                  -86.78494145733295,
                  33.12348397509187,
                  67
                ],
                [
                  -86.78518499014336,
                  33.122430188528,
                  56
                ],
                [
                  -86.78356143807218,
                  33.12282111082557,
                  56
                ],
                [
                  -86.78345996606778,
                  33.12090047585342,
                  56
                ],
                [
                  -86.78205965240596,
                  33.12146137359524,
                  56
                ],
                [
                  -86.78281054523904,
                  33.124418775169175,
                  56
                ],
                [
                  -86.78494145733295,
                  33.12348397509187,
                  67
                ]
              ]
            ],
            type: "Polygon"
          }
        },
      ]
    }

const { shp, shx, dbf } = await shpKit.shpWrite(geojson, 'PolyLineZ');

let zip = new JSZip();
    zip.file('regions.shp', shp);
    zip.file('regions.shx', shx);
    zip.file('regions.dbf', dbf);
    console.log('zip', zip)
    const zipBuffer = await zip.generateAsync({ type: "arraybuffer" });

    // Set appropriate headers for ArrayBuffer response
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', 'attachment; filename=regions.zip');

    // Send the ArrayBuffer as the response body
    return res.send(Buffer.from(zipBuffer));
```

**Comment by abrman** [comment] 2024-11-12 17:53
Sounds like a valid bug. 
Can't give you a definite time I'll have time to resolve, but if you have time don't hesitate to have a crack at it and submit a PR, any help will be appreciated.

It's likely part of `shpLength` function in [shp-kit/src/private/writers/PolyLine.ts](https://github.com/abrman/shp-kit/blob/ae33d67a1cfabb4628639e22b9cf647f612f7c61/src/private/writers/PolyLine.ts)
This is the function determining the resulting shapefile byte size (canvas size) - should be consistent with the whitepaper [Shapefile](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf)

If the bug isn't there it's somewhere in the rest of the code in the file where an attempt is being made to write to a out of range location, maybe an offset isn't being passed correctly, but I understand the complexity of tracking this bug might not be something you're up for. 

If it seems like a too big of a nut to crack, try to see if the same issue happens with multipolygon as multilinestring is tested with polylineZ writer and the tests pass, although the tests are limited in scope, so it might be a hit or miss.

**Comment by traik06** [comment] 2024-11-12 19:02
@abrman 

I might have been mistaken I was able to get two polygons with `PolyLineZ` just was not able to get two polyons with `PolygonZ`

**Comment by abrman** [comment] 2024-11-12 19:04
@traik06 I think there's a bug though, I'm trying to run some tests for the polyline writer right now and am running into `RangeError: Offset is outside the bounds of the DataView` I will keep you posted on my findings.

**Comment by traik06** [comment] 2024-11-12 19:27
> @traik06 I think there's a bug though, I'm trying to run some tests for the polyline writer right now and am running into `RangeError: Offset is outside the bounds of the DataView` I will keep you posted on my findings.

Okay sounds great thank you

**Comment by abrman** [comment] 2024-11-12 21:16
@traik06 I believe I found the bug

in the beforementioned `shxLength` function 
the `16` and `32` in the `PolylineM` and `PolylineZ` respectively need to be multiplied by features count (this is because shapefile internally stores minmax on each axis on the feature level, rather than the shapefile level. Good catch.

Should look something like this on your end:
```js
if (typeString === "PolygonZ") polyline_record_length_bytes += features.length * 32 + coordinates.length * 16;
```

Let me know if this resolves the issues you've been having!

**Comment by traik06** [comment] 2024-11-12 21:21
Is this also the fix to the issue of only one polygon showing

**Comment by abrman** [comment] 2024-11-12 21:37
I believe so, it worked with Polyline so I would assume so.

**Comment by traik06** [comment] 2024-11-13 19:48
@abrman 
It seems to have worked for me. I am going to do some more testing to verify that everything I'm trying to do is working correctly

**Comment by traik06** [comment] 2024-11-14 17:58
@abrman 

Its working properly! 

My other question now is there a way to create a `.prj` file to set a coordinate system? If so would this be the correct way?

``` javascript
    const wktProjectionString = 'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]'
    const regions = req.body;

    const geojson = {
      type: 'FeatureCollection',
      features: [],
    };

    regions.forEach((region) => {
      const coords = region.boundaries.map((point) => {
        return [point.lng, point.lat, point.elevation || 0];
      });

      const template = {
        type: 'Feature',
        properties: {
          name: region.name,
        },
        geometry: {
          coordinates: [coords],
          type: 'Polygon',
        },
      };

      geojson.features.push(template);
    });

    const { shp, shx, dbf } = await shpKit.shpWrite(geojson, 'PolygonZ');

    const zip = new JSZip();
    zip.file('regions.shp', shp);
    zip.file('regions.shx', shx);
    zip.file('regions.dbf', dbf);
    zip.file('regions.prj', wktProjectionString);
    const zipBuffer = await zip.generateAsync({ type: 'arraybuffer' });
```

Would you also be open for me opening a PR and developing code to specific 3D Polygons with no inner rings?

**Comment by abrman** [comment] 2024-11-14 18:51
`.prj` is basically a `WKT` representation of geometry projection/coordinate system. It shouldn't be too difficult to create.

Let's say you want your source polygon with coordinates in WGS84 coordinate system, and you'd like to have your shapefile in NAD83 state plane. You could use the `reprojectGeoJson` function exposed by `shp-kit` to get your geojson into another coordinate system, then run this geojson through shpWrite and the `.prj` file you'd have to add would contain the projection WKT definition.

To get the target projection WKT I'd go and use [epsg.io](https://epsg.io) and find the coordinate system I'm interested in using - for example [NAD83 / New York East (ftUS)](https://epsg.io/2260) and scroll a bit down on the page. The [OGC WKT 2](https://epsg.io/2260.wkt2) should work as the content of your .prj file.

`shp-kit` is using `proj4` to work with projections and reprojections of geometry into another system. This works most of the time but there are some edge cases where it hasn't worked properly. I've looked into `mapshaper` [implementation](https://github.com/mbloch/mapshaper/blob/c18936117413f6a90c53e54794a0e27569fd1056/src/commands/mapshaper-proj.mjs#L26) of projection systems and it seems to work better, although I wasn't able to implement it into `shp-kit` yet (need to check license too).

> Would you also be open for me opening a PR and developing code to specific 3D Polygons with no inner rings?

I'm still not sold for the idea of minimal support with no thrown errors, fingers crossed shapefile generates correctly if that's what you have in mind. I'm glad we were able to remove a bug and fit your use-case (Assuming you have full control of the geometry that comes in, you should be able to avoid the caveats)

Please don't forget to star the repo so other's might consider it in the future, and as always, feel free to reach out with any additional questions or comments. I'm closing this issue as you seem to have reached a working prototype. 👍 

---------------------------------

If you would want to tackle a wider support and testing as described in my previous [comment](https://github.com/abrman/shp-kit/issues/11#issuecomment-2458059848) that would be **HUGE** for anyone considering `shp-kit` in the future.  - Specifically: 
- Reverse polygon orientations per shapefile specifications - clockwise/counterclockwise (mid-hard complexity)
- Throw error/log notice when polygons are intersecting and if possible unkink them, notes below (mid complexity)
- Log notice when ring isn't closed and close it (easy)
- Remove redundant points and log notice if action performed (easy)

Luckily this doesn't carry any overhead of binary encoding for the shapefile format, mostly just geometry analysis and corrections.

Additional notes if you are down for this endeavor, although feel free to tackle the problem any other way.

- Check intersections:
  - Between multiple lineStrings of a single polygon - I'd probably just go ahead and use https://turfjs.org/docs/api/lineOverlap, throw error
  - Self-intersection of a single lineString of a polygon- https://turfjs.org/docs/api/kinks, use https://turfjs.org/docs/api/unkinkPolygon and log notice
- Determine which polygon is inside of which polygon - https://turfjs.org/docs/api/booleanWithin
- Determine orientation of polygon
  - I've written a blender python add-on where I needed to determine if a loop is clockwise or not. Shoelace Formula or Gauss's Area Formula proved to be instrumental to determine orientation of a given polyline. Below is my implementation if you read code better than papers. 😄 

```py
def make_loop_clockwise(loop): 
    def is_loop_clockwise(loop):
        signed_area = 0.0        
        # Iterate through the vertices in the loop
        for i in range(0, len(loop) - 1, 2): # Contains both vertices and edges, that's why we iterate +=2
            vert1 = loop[i]
            vert2 = loop[i + 2] if i + 2 < len(loop) else loop[0]  # Handle the last segment closing the loop
            
            # Vertices coordinates
            x1, y1 = vert1.co.x, vert1.co.y
            x2, y2 = vert2.co.x, vert2.co.y

            # Calculate contribution to the signed area
            signed_area += (x2 - x1) * (y2 + y1)
        
        # If the signed area is negative, it's clockwise; if positive, it's counterclockwise
        return signed_area < 0
    if not is_loop_clockwise(loop): loop.reverse()        
    return loop
```

**Comment by abrman** [comment] 2024-11-14 18:53
Seeing your implementation edit, LGTM.
Assuming `wktProjectionString` is valid and coordinates are in given coordinate system.

Closing.

**Closed as completed by abrman** 2024-11-14 18:53 UTC
